# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1yr9p8rf2njrp5q2zfphfssr7ybirxzkw8zqaigx93mlsjqd7dvj";
    aarch64-linux = "0fw53fnp8yf2qzbwcss50gnhpixxrz0x4arl0lf4lsxnf0i0ahdm";
  };

  urlMap = {
    x86_64-linux = "https://github.com/nickheyer/GreetDeez/releases/download/v1.0.37/greetdeez_1.0.37_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/nickheyer/GreetDeez/releases/download/v1.0.37/greetdeez_1.0.37_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "greetdeez";
  version = "1.0.37";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./greetdeez $out/bin/greetdeez
  '';

  meta = {
    description = "Minimal, hackable display manager greeter for greetd";
    homepage = "https://github.com/nickheyer/greetdeez";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
